# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{falcon}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Igor Galeta", "Pavlo Galeta"]
  s.date = %q{2011-05-24}
  s.description = %q{Background video encoding via resque}
  s.email = %q{galeta.igor@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "app/models/falcon/encoding.rb",
    "lib/falcon.rb",
    "lib/falcon/base.rb",
    "lib/falcon/encoder.rb",
    "lib/falcon/engine.rb",
    "lib/falcon/media.rb",
    "lib/falcon/profile.rb",
    "lib/falcon/profiles.rb",
    "lib/falcon/version.rb",
    "lib/generators/falcon/USAGE",
    "lib/generators/falcon/install_generator.rb",
    "lib/generators/falcon/templates/migrate/create_encodings.rb"
  ]
  s.homepage = %q{https://github.com/galetahub/falcon}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Background video encoding}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<web_video>, ["~> 1.1.1"])
    else
      s.add_dependency(%q<web_video>, ["~> 1.1.1"])
    end
  else
    s.add_dependency(%q<web_video>, ["~> 1.1.1"])
  end
end

